### ISSUE TITLE
How to validate/prevent invalid state transitions in ClassifiedAd?

### ISSUE THREAD

**Issue by ghandmann** [PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET#10]
Hi!
I really enjoyed the book so far. I just started to play around with what you teach and how to use the whole DDD-Framework-Classes to fiddle around with my own business case.

And now i stumbled upon the problem, that i have no idea on how to prevent an invalid state transition inside my aggregate.

Let's imagine my boss decides, that a `ClassifiedAd` once published shall not be changed. Meaning setting the title and text should not be possible anymore. I currently don't see how this use case could be solved with the current foundation based on the `AggregateRoot.Apply()` method, since it would just update the text via the `When()` method. Afterwards it would call the `EnsureValidState()` method which would be totally fine. Additionally `EnsureValidState()` is unable to detect this change at all. So we push the new Event into our local changes and everything would look fine. Beside the fact that we changed the title of an already published ad which we don't want to allow.

So the only two possible options to solve this i see are:
1) Validate the state transition inside of the setter. So calling `SetTitle` when in the `Published`-State would not emit a new event. Prevent the update. But this feels wrong, since we tried to centralize the whole validation with the `EnsureValidState` method.
1) Check if it's valid to change the title inside the `When()` method when processing a `TitleChangedEvent`. This would work, as long as we don't try to replay old Event-Streams which were created before we chnged the rules. So we generally don't want to validate inside of `When()`.

Could you please share some advice on how to do this? Or is this even something that should not be placed inside the Aggregate but more like the surrounding Manager?

**Comment by alexeyzimarev** [comment]
There's no rule that all checks should be in `EnsureInvalidState`. Using one consolidated invariant control check is an option, not a rule.

Overall, there are several layers of checks:

- Edge check - prevent invalid values from reaching the app service: numbers should be numbers, ranges should be valid, strings not empty, dates should be dates and so on
- Application layer check - at least ids should point to existing objects, or uniqueness should be guaranteed with the best effort, and so on
- Aggregate pre-check - don't execute operations that are obviously incorrect, considering the aggregate state
- Aggregate post-check - ensure that the aggregate state is valid after the operation has been executed

Basically, the last two points are the essence of what aggregates are for - to ensure consistency.

Concerning any checks in `When` - I believe I mentioned that it should _never_ be done. `When` is called when an event already happened. There's no way you can say "no" to something that already happened. Having _any_ checks in `When` directly leads to situations that your aggregate simply won't load.

In the Chapter 13 code, I made a small adjustment for `EnsureValidState`. It gives you the old state and the new state, so you can see if there was any change that is not desired. So, you can achieve your goal very easily by checking if the ad state was `Published` and the title has changed, so you can throw an exception.

**Comment by alexeyzimarev** [comment]
Hmm, I can't find this code now but I am sure I have it somewhere. I will definitely put it there.

**Comment by ghandmann** [comment]
Thanks for your quick response!

> * Edge check - prevent invalid values from reaching the app service: numbers should be numbers, ranges should be valid, strings not empty, dates should be dates and so on
> * Application layer check - at least ids should point to existing objects, or uniqueness should be guaranteed with the best effort, and so on
> * Aggregate pre-check - don't execute operations that are obviously incorrect, considering the aggregate state
> * Aggregate post-check - ensure that the aggregate state is valid after the operation has been executed
> 
> Basically, the last two points are the essence of what aggregates are for - to ensure consistency.

Ahh ok, that sounds reasonable. :) So is there any considerable draw-back of putting such a pre-check into he setter of the aggregat itself? Because currently i don't see any other place which would create the DomainEvents. So preventing the setter from creating it, should prevent the occurrence completely, right?

Or is it beneficial to go with a more sophisticated `PreCheckEnsureValidate` method placed inside the `AggregateRoot.Apply` method?

> Concerning any checks in `When` - I believe I mentioned that it should _never_ be done. `When` is called when an event already happened. There's no way you can say "no" to something that already happened. Having _any_ checks in `When` directly leads to situations that your aggregate simply won't load.

Indeed you mention this in the Book. That's why i ruled it out in my original post. (But re-reading it now, it sounds like i came up with the rule by myself :smiley:)

I would be very interested in the missing Chapter13 code regarding new and old state for `EnsureVallidState`. :wink:

**Comment by alexeyzimarev** [comment]
I found out that it's there:

https://github.com/PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET-Core/blob/master/Chapter13/src/Marketplace.EventSourcing/AggregateState.cs#L39

And here is how it's used:
https://github.com/PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET-Core/blob/0bba3969ccb17b01671e4c122f7ef9a3ad33cb52/Chapter13/src/Marketplace.PaidServices.Domain/Orders/OrderState.cs#L41-L49

So, the entity has its current state still, the `Apply` method only changes the new state (immutable). The `EnsureValidState` can compare the current and the new state to decide if the change is valid.
