### ISSUE TITLE
Question on user and tenant details

### ISSUE THREAD

**Issue by jorgeolive** [PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET#11]
Hello Alexey. 

Great book. I've put a great deal of time to it. Needless to say, I would recommend it without any doubt to anyone who has interest to dive deep into DDD straight away.

I have one question that is not touched in the book, and it would be great if you can share some high level guidelines on what would be your approach on it. I am talking about tenancy and entity user related information -eg who created the record, when, related tenant - Not sure where this should be. Perhaps extending the Entity and Agregatte root classes? Makes sense to me but it kind of pollutes these entity boundaries. 

Thanks,
Jorge.

**Comment by alexeyzimarev** [comment]
We usually include these properties in commands and events.

For example:

```csharp
public class UpdateText
{
    public Guid           Id        { get; set; }
    public string         Text      { get; set; }
    public string         UpdatedBy { get; set; }
    public DateTimeOffset UpdatedAt { get; set; }

    public override string ToString() => $"UpdateText {Id} {Text}";
}
```

This information doesn't necessarily need to be a part of any entity, unless you have some logic that is using it.
