### ISSUE TITLE
Possible projection corruption?

### ISSUE THREAD

**Issue by dt665m** [PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET#17]
I'm still new to EventStore so maybe I'm missing something about the catchup subscription... but in the subscription manager, the projection stores and the checkpoint store aren't transactional so if a crash occurs right after projection handlers complete but before the checkpoint store completes, wouldn't you get double processing in the projections the next time the application restarts?

https://github.com/PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET-Core/blob/5cacfbfa68933a00307c43639a12a0805338b46a/Chapter13/src/Marketplace.EventStore/SubscriptionManager.cs#L71

**Comment by alexeyzimarev** [comment]
Your observation is correct. There are many types of persistence that do not support transaction across collections, datasets, and so on. Think about previous versions of MongoDB or Redis as examples.

Therefore, my advice is to make projections idempotent, so you can project one or more events again without producing undesired side effects. Such an approach would also help if you decide to delay the checkpoint update. This operation seems to be small and fast, but when dealing with lots of IO, you'd want to save on the smallest bits.

I prefer not to have any calculations or logic in projections. Alternatively, I keep something like the timestamp or projected event version, so I can ignore duplicate events.

**Comment by gaurav-packt** [comment]
Closing the issue as per the feedback shared by the author
