### ISSUE TITLE
"protected override void EnsureValidState()" in chapter 5.

### ISSUE THREAD

**Issue by XristosKatsikas** [PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET#18]
a) "override" gives an error.
b) The compiler in VS 2017 gives errors regarding the content of the method. 
"Operator '&&' cannot be applied to operands of type 'bool' and type'.....' ".
Also it gives errors regarding missing parenthenses and ";".

**Comment by alexeyzimarev** [comment]
The repository code uses C# 8, which is not supported by VS 2017.

**Comment by XristosKatsikas** [comment]
Hi,

In chapter 8, regarding the creation of a postgres database, do we need the
docker-compose up command in the cmd?
If yes, why i take the message:
" invalid mount config for type "bind": bind source path does not exist:
c:\...\marketplace\init.sql"

PS: I have windows 10 on my laptop.

Best regards,
Christos Katsikas

Στις Τετ, 22 Ιουλ 2020 στις 12:53 μ.μ., ο/η Alexey Zimarev <
notifications@github.com> έγραψε:

**Comment by alexeyzimarev** [comment]
@XristosKatsikas how is it related to the original issue?

**Comment by XristosKatsikas** [comment]
It is not related to the original issue.

It is an issue that I have by means of trying to use PostgreSql.


Στις Κυρ, 25 Οκτ 2020 στις 7:26 μ.μ., ο/η Alexey Zimarev <
notifications@github.com> έγραψε:

**Comment by alexeyzimarev** [comment]
It's better to open a new issue rather than communicating in an unrelated issue.
