### ISSUE TITLE
Chapter 5 Unit Tests dont run

### ISSUE THREAD

**Issue by syvers147** [PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET#20]
Hi,
The unit tests cannot run in chapter 5. I have even resorted to copying and pasting from here but they fail. The reason is each Event Applied raises the EnsureValidState method and the state is not valid from the very first call.

For example
`public void Cannot_publish_without_price()
        {
            _classifiedAd.SetTitle(ClassifiedAdTitle.FromString("Test ad"));
            _classifiedAd.UpdateText(ClassifiedAdText.FromString("Please buy my stuff"));
            Assert.Throws<InvalidEntityStateException>(() => _classifiedAd.RequestToPublish());
        }`

when that test is run it fails on the first line due to

```
protected void Apply(object @event)
        {
            When(@event);
            **EnsureValidState();**
            _events.Add(@event);
        }

```
the state of the Ad is not yet valid so the exception is thrown before it gets to the assert.

What do you recommend?

**Comment by alexeyzimarev** [comment]
I am not sure what the issue is since I cloned the repo and it runs like this:

```
➜  Chapter05 git:(master) ✗ dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  Marketplace.Framework -> /Users/alexey/dev/books/packt-ddd/packt-repo/Chapter05/Marketplace.Framework/bin/Debug/netstandard2.0/Marketplace.Framework.dll
  Marketplace.Domain -> /Users/alexey/dev/books/packt-ddd/packt-repo/Chapter05/Marketplace.Domain/bin/Debug/netstandard2.0/Marketplace.Domain.dll
  Marketplace.Tests -> /Users/alexey/dev/books/packt-ddd/packt-repo/Chapter05/Marketplace.Tests/bin/Debug/netcoreapp3.1/Marketplace.Tests.dll
Test run for /Users/alexey/dev/books/packt-ddd/packt-repo/Chapter05/Marketplace.Tests/bin/Debug/netcoreapp3.1/Marketplace.Tests.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

Test Run Successful.
Total tests: 14
     Passed: 14
 Total time: 13.6276 Seconds
```

**Comment by alexeyzimarev** [comment]
I also don't really understand why it should fail _before_ the assertion.

These lines produce valid state:

```csharp
_classifiedAd.SetTitle(ClassifiedAdTitle.FromString("Test ad")); 
_classifiedAd.UpdateText(ClassifiedAdText.FromString("Please buy my stuff"));
```

The `Assert.Throws` expects the passed function to throw, which it does, since `_classifiedAd.RequestToPublish()` will make the state of the aggregate invalid.

If by "throwing" you mean that you get your debugger stop on the exception line in Visual Studio, it is the debugger setting. Press F5 and it will pass the test.

**Comment by syvers147** [comment]
Hi
Thanks for replying very quickly. It is my mistake. I didn't have a line of code as follows: State = ClassifiedAdState.Inactive; in the classifiedAd constructor. When I was debugging I thought it was SetTitle that was erroring but in fact it was in the constructor but I had no breakpoint there and was just shooting straight past it.
Please accept my apologies. In future I will clone then debug side by side at the first instance.

**Comment by alexeyzimarev** [comment]
No worries, I'm glad that you figured out the issue.
