### ISSUE TITLE
[Question] Remove picture form database

### ISSUE THREAD

**Issue by ahmadasm** [PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET#21]
How to remove a picture from database?

**Comment by alexeyzimarev** [comment]
I am not sure what you mean here, sorry.

**Comment by ahmadasm** [comment]
I read your book and follow the instructions, but right now I want to remove a picture from classifiedad. I could remove it from domain model but it remains in database.

**Comment by alexeyzimarev** [comment]
In what database? There are at least three database types used in the book.

**Comment by deepesh-packt** [comment]
Please reopen if the issue still persists.
