### ISSUE TITLE
For those looking for missing chapter 13

### ISSUE THREAD

**Issue by Kevdome3000** [PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET#28]
Not sure why this chapter wasn't included in the book or why a link wasn't provided by Packt, but here it  is:

https://static.packt-cdn.com/downloads/Splitting_the_System.pdf

**Comment by shubham763** [comment]
Hi @Kevdome3000 

Chapter 13 link is present in the preface of the book.

Regards,
Shubham
