### ISSUE TITLE
Chapter 13

### ISSUE THREAD

**Issue by chokoelesibana** [PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET#31]
Hi

i am trying to run chapter13 solution but the program blows up on this line of code.
// Everything we proxy is hardcoded to target http://localhost because:
            // - the requests are always from the local machine (we're not accepting remote
            //   requests that go directly to the create-react-app server)
            // - given that, there's no reason to use https, and we couldn't even if we
            //   wanted to, because in general the create-react-app server has no certificate
            **var targetUriTask = portTask.ContinueWith(
                task => new UriBuilder("http", "localhost", task.Result).Uri
            );**

Below is the error
System.AggregateException: 'One or more errors occurred. (The NPM script 'serve:bs' exited without indicating that the Vue development server was listening for requests.

**Comment by shruthis-shetty** [comment]
Hey @chokoelesibana , I'm from Packt.
According to author, the book got published few years ago so this would be issue related to your local environment or not following the instructions. Also, with time some NPM packages might get removed from NPM, and it would not be possible to restore. Please do look into these things. Let me know if you still have any issues. I'll be closing this issue for now.
