### ISSUE TITLE
Missing chapter 13

### ISSUE THREAD

**Issue by fuine6** [PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET#4]
I bought this book.
But did not see the 13th chapter.

**Comment by alexeyzimarev** [comment]
Thank you for buying the book, I hope you like it!

About the final chapter, please check my post: https://zimarev.com/post/2019-06-01-ui-part-of-the-book/

**Comment by fuine6** [comment]
I really like this book.
I am looking forward to the chapter.
