### ISSUE TITLE
Separating the Domain Models from Data Models

### ISSUE THREAD

**Issue by Milad101** [PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET#5]
Is it okay to separate the domain models and data models and instead use translators/mapper to convert one to another?
Although when we create the domain models we use the methods of the domain models e.g SetTitle so we ensure that the domain model is in good shape. but what happens when EF retrieves the data from db and through reflection sets the property values while someone made a mistake and changed the data directly on the DB? That bad data for instance in a finance application can cause lots of miscalculations till someone realizes it.

**Comment by alexeyzimarev** [comment]
Absolutely. The persistence model has little to nothing to do with the domain model. I used the approach which was simplest to implement, with documents and an ORM framework, but those are just options. As you find in event sourcing chapters, there the persistence has no translations.

**Comment by gaurav-packt** [comment]
Thanks for the feedback; with this I'm closing the issue.
